openapi: 3.0.1
info:
  title: Course Manager - API
  description: API de Gerenciamento de Cursos
  version: 1.0.0
servers:
- url: http://localhost:8282

tags: 
  - name: Student-Controller
  - name: Course-Controller
  - name: Enrollment-Controller

paths:
  /students:
    post:
      tags:
      - Student-Controller
      operationId: createStudent
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StudentRequestDto"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/StudentResponseDto"
  /enrollments:
    post:
      tags:
      - Enrollment-Controller
      operationId: createEnrollment
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EnrollmentRequestDto"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/EnrollmentResponseDto"
  /courses:
    post:
      tags:
      - Course-Controller
      operationId: createCourse
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CourseRequestDto"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/CourseResponseDto"
  /students/{studentId}/courses:
    get:
      tags:
      - Student-Controller
      operationId: getCoursesByStudentId
      parameters:
      - name: studentId
        in: path
        required: true
        schema:
          type: integer
          format: int32
          example: 1
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CourseResponseDto"
  /courses/{courseId}/students:
    get:
      tags:
      - Course-Controller
      operationId: getStudentsByCourseId
      parameters:
      - name: courseId
        in: path
        required: true
        schema:
          type: integer
          format: int32
          example: 1
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/StudentResponseDto"
components:
  schemas:
    StudentRequestDto:
      type: object
      properties:
        name:
          type: string
          example: 'John Doe'
        description:
          type: string
          example: 'Estudante de Tecnologia'
        creationDate:
          type: string
          format: date-time
          example: '2024-11-14T14:15:41'
    StudentResponseDto:
      type: object
      properties:
        id:
          type: integer
          format: int32
          example: 1
        name:
          type: string
          example: 'John Doe'
        description:
          type: string
          example: 'Estudante de Tecnologia'
        creationDate:
          type: string
          format: date-time
          example: '2024-11-14T14:15:41'
    EnrollmentRequestDto:
      type: object
      properties:
        studentId:
          type: integer
          format: int32
          example: 1
        courseId:
          type: integer
          format: int32
          example: 1
        registrationDate:
          type: string
          format: date-time
          example: '2024-11-14T14:15:41'
    EnrollmentResponseDto:
      type: object
      properties:
        id:
          type: integer
          format: int32
          example: 1
        registrationDate:
          type: string
          format: date-time
          example: '2024-11-14T14:15:41'
    CourseRequestDto:
      type: object
      properties:
        name:
          type: string
          example: 'John Doe'
        description:
          type: string
          example: 'Estudante de Tecnologia'
        creationDate:
          type: string
          format: date-time
          example: '2024-11-14T14:15:41'
    CourseResponseDto:
      type: object
      properties:
        id:
          type: integer
          format: int32
          example: 1
        name:
          type: string
          example: 'Java Spring Boot'
        description:
          type: string
          example: 'Curso de Tecnologia'
        creationDate:
          type: string
          format: date-time
          example: '2024-11-14T14:15:41'
